### ISSUE TITLE
How to generate obj file with my own image

### ISSUE THREAD

**Issue by XieBinghui** [XgTu/2DASL#11]
Thanks for your work！Would it be possible for you to tell me how to get the obj file with my own images

**Comment by XgTu** [comment]
@XieBinghui 
Hi, I have uploaded the matlab code for write object, under the folder "3D_results_plot", pls refer to script "write_objs.m"

**Comment by XieBinghui** [comment]
Thanks for your reply. It seems that I need vertex.mat for my image to get the obj file. But if I only have  some simple images, how to get the obj files I need. Thanks for your assistance!
