### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cleardusk** [XgTu/2DASL#3]
Please add the MIT license because you use the code in [3DDFA](https://github.com/cleardusk/3DDFA), which is under the MIT license.

**Comment by XgTu** [comment]
Thanks 

> Please add the MIT license because you use the code in [3DDFA](https://github.com/cleardusk/3DDFA), which is under the MIT license.

Thanks cleardusk,

**Comment by XgTu** [comment]
Dear Jianzhu,


Thanks for your kind reminder, I have added the MIT license as you suggested.


Xiaoguang





At 2019-04-15 17:58:11, "Jianzhu Guo" <notifications@github.com> wrote:


Please add the MIT license because you use the code in 3DDFA, which is under the MIT license.
