### ISSUE TITLE
How to get the forth channel of input data?

### ISSUE THREAD

**Issue by xinghuokang** [XgTu/2DASL#8]
Hi, I want to test my own image, but input of model is four channels, and how to get the forth channel of my own data? 
Thanks

**Comment by XgTu** [comment]
@xinghuokang 
The additional channel is a binary-value image, where the locations corresponding to facial landmarks take the value of 1 and others take the value of −1

**Comment by xinghuokang** [comment]
Thank you for your reply, how to get facial landmarks of  my own image, by others libarary?

**Comment by XgTu** [comment]
@xinghuokang 
You can use mtcnn or 2D FAN or dlib to obtain the landmarks.

**Comment by xinghuokang** [comment]
Thanks
